start: definition* target+

definition: IDENTIFIER "(" param_list? ")" ":=" expression ";"

param_list: IDENTIFIER ("," IDENTIFIER)*

target: ">" expression "as" IDENTIFIER "(" param_w_type_list? ")" "->" TYPE ";" -> generate_target

param_w_type_list: TYPE IDENTIFIER ("," TYPE IDENTIFIER)* -> generate_param_with_type_list

?expression: "if" condition "then" expression ("elif" condition "then" expression)* "else" expression -> if_struct
           | expr

?condition: log_and ("or" log_and)* -> logic_or
?log_and: comparison ("and" comparison)* -> logic_and

?comparison: BOOL_CONST -> bool_const
           | expr REL_OP expr -> cond_op
           | "(" condition ")"

?expr: term (ADD_OP term)* -> add
?term: factor (MUL_OP factor)* -> prod
?factor: "-" factor -> negate
       | power
?power: atom ("^" power)? -> power

?atom: NUMBER -> float_num
     | IDENTIFIER -> variable
     | function_call
     | shorthand
     | derivative
     | "(" expression ")"

function_call: IDENTIFIER "(" arg_list? ")" -> function_call
arg_list: expr ("," expr)*

shorthand: SHORTHAND_TYPE "(" IDENTIFIER FROM INT TO INT ":" expression ")" -> shorthand
derivative: "diff" "(" IDENTIFIER "," INT "," expression ")" -> differentiate

BOOL_CONST.2: "true" | "false"

TYPE.2: "double" | "float" | "int"
REL_OP: "==" | "!=" | ">" | "<" | ">=" | "<="
MUL_OP: "*" | "/"
ADD_OP: "+" | "-"
SHORTHAND_TYPE.2: "sum" | "prod"
FROM.2: "from"
TO.2: "to"

%import common.CNAME -> IDENTIFIER
%import common.NUMBER
%import common.INT
%import common.WS
%ignore WS
