start: definition_list target

definition_list: definition*
definition: IDENTIFIER "(" param_list? ")" ":=" b_expr ";"

param_list: IDENTIFIER ("," IDENTIFIER)*

target: ">" b_expr ";" IDENTIFIER ";" TYPE

?b_expr: "if" condition "then" b_expr ("elif" condition "then" b_expr)* "else" b_expr
      | expr
 
!rel_op: "==" | "!=" | ">" | "<" | ">=" | "<="

?expr: term (("+" | "-") term)*
?term: power (("*" | "/") power)*
?power: atom ("^" power)?

?atom: NUMBER          -> number
     | IDENTIFIER      -> var
     | function_call
     | shorthand
     | "(" b_expr ")"

function_call: IDENTIFIER "(" arg_list? ")"
arg_list: expr ("," expr)*

!shorthand: ("sum" | "prod") "(" IDENTIFIER ";" expr ";" expr ";" expr ")"

TYPE: "double" | "float" | "int"
%import common.CNAME -> IDENTIFIER
%import common.NUMBER
%import common.WS
%ignore WS
